### ISSUE TITLE
Porting over to Eloquent

### ISSUE THREAD

**Issue by acxz** [RobotnikAutomation/summit_xl_common#11]
It would be great if these packages can have a ROS 2 port. Are there any plans for porting the Summit pipeline to ROS 2 Eloquent?

**Comment by RomanRobotnik** [comment]
Hi,

Unfortunately there are no plans to for moving to ROS 2 yet... sorry!

**Comment by acxz** [comment]
I see. I hope you guys change your mind. ROS2 offers real--time support which is very enticing and useful for many critical projects. Thank you!
