### ISSUE TITLE
About docking

### ISSUE THREAD

**Issue by isValid** [RobotnikAutomation/summit_xl_common#14]
When I use automatic charging, I received a warning:
"I cannot calculate relative twist between summit_xl_base_docking_contact_link -> summit_xl_docking_station_contact, probably due to a high goal averaging time."
Why does this message appear and what results will it cause？And how to solve it ？

**Comment by RomanRobotnik** [comment]
Hi,

Do you see this warning before performing the dock to charge or when it has finished? is it appearing continuously or just few times and then stop? 

Normally this message is related to fact that the robot is not seeing the 'marks' (AR marker and/or reflector) of the station.
