### ISSUE TITLE
Porting over to Melodic

### ISSUE THREAD

**Issue by acxz** [RobotnikAutomation/summit_xl_common#7]
Hello, I am wondering if this repo will be packaged as a Melodic package, and if so when? I am interested in getting this code to work in Melodic and I would love to use packages instead of compiling the source code.

**Comment by RomanRobotnik** [comment]
Hi,

The migration to Melodic is planned to be done during this year. I give you an exact date yet, sorry!

**Comment by acxz** [comment]
Thank you for responding! Can there be a branch made for melodic? As I am working on the source code it would be great if there is a branch I can submit issues and PRs to.

**Comment by JackBonnellDevelopment** [comment]
Hi i am trying to run the summit xl on melodic and i am only getting these errors since upgrading to ubuntu 16.4 and melodic. The velocity is set to max and there seems to be no steering the image below shows the errors that are being shown in the main console and the  .../robotnik_base_hw/status topic.
![logs](https://user-images.githubusercontent.com/22745183/60887876-48daef80-a24d-11e9-8021-0eea0dc01b13.png)

**Comment by jgomezgadea** [comment]
Hi,

I'm not sure if I've understood your question correctly, but I think that kinetic is not supported in Ubuntu 18.04. [Here](http://www.ros.org/reps/rep-0003.html#melodic-morenia-may-2018-may-2023) you will find the different versions along with their Ubuntu versions.  

The terminal has no error messages, there are info and warn messages (and it's working correctly).

The steering problem seems a problem with the configuration of your robot (on ~/robot_params.env). Make sure you have set the params correctly according with your robot. If you don't know the configuration of your model, contact with [support@robotnik.es](support@robotnik.es) giving us the serial number of your robot.

**Comment by acxz** [comment]
I believe this issue has been incorrectly closed since this package has not been ported over to melodic.

**Comment by jgomezgadea** [comment]
> I believe this issue has been incorrectly closed since this package has not been ported over to melodic.

Hi @acxz , I think the question asked on this issue has been answered. If you have another question related with this, do not hesitate to ask. 

As soon as we could, we will create a new branch for melodic.

**Comment by acxz** [comment]
My question has been addressed with your last comment. Although I believe this issue should remain open until that branch is made, for the sake of project trace-down, but I understand if you want to close this issue.
